### ISSUE TITLE
Add state logic to Create button

### ISSUE THREAD

**Issue by thisisdano** [harvard-lil/perma#1066]
The new Create button has three states:

1) **Inactive:** Field is empty (gray button, not clickable)

![field block-off](https://cloud.githubusercontent.com/assets/11464021/9990947/a8c9022a-6033-11e5-9e4f-6f244dff59ae.png)

2) **Active:** Field includes a URL (blue button, clickable)

![field block](https://cloud.githubusercontent.com/assets/11464021/9990954/c10958ee-6033-11e5-8920-f48a2cf7b1ca.png)

3) **Working:** Perma.cc is creating the Perma Link (spinner with text)

![field block-creating](https://cloud.githubusercontent.com/assets/11464021/9990968/e366226e-6033-11e5-8fab-b40b7e6f2b00.png)

When the record is ready we redirect to the the Record page.
Errors can still appear below as they do now.

**Comment by phillipsm** [comment]
I prototyped the inactive/active (on URL validation) create button interaction and it felt restrictive and not terribly helpful to the user.

This type of interactive design would be great if the URL field were part of a bigger form, but since it's the only thing, it feels more natural to let the user do whatever, and display an error below if things go sideways.

Kicking this down a milestone. Maybe it'll feel better upon revisit.
