### ISSUE TITLE
Registrar User Can't Delete Orgs

### ISSUE THREAD

**Issue by cdemarco** [harvard-lil/perma#1188]
I'm logged in as a Registrar User, and although I can edit the names of the vesting orgs, I can't delete them.  Shouldn't Registrar Users have that power?

**Comment by anniejocain** [comment]
should orgs be deletable?
what happens to associated links?
what happens to org members?

**Comment by jcushman** [comment]
Links can be moved between orgs, right? I think it makes sense to allow orgs to be deleted if there are no links in their folder. Then if you had a Harvard Law Review org and a Havrard Law Review org, you could consolidate the links into one and delete the other. Org members lose the association with that org but aren't otherwise affected.

**Comment by anniejocain** [comment]
Works for me.
