### ISSUE TITLE
Links remaining is broken because of 2015 year check

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1328]
@jcushman can you explain this bit of code to me? 
in models.py `get_links_remaining` method, line 260, there's a note about a "temp hack for mid-month deployment"
We're checking for the year 2015 which now should obviously be incremented or the method should be rewritten. Why would this check be required?

**Comment by jcushman** [comment]
Is it broken, like failing to return correct count for this month, or does it just not run that line anymore? The point was to add a special date check for Dec. 2015, since we deployed mid-month and didn't want to count links created before the deployment. We can now remove the 'if' and just keep the 'else' branch.

**Comment by anastasia** [comment]
Huh. Seems to be broken just on my local — looking up links by month (`creation_timestamp__month`) doesn't work. Perma stage looks correct, though! Gotta do a version sweep of my dependencies.
