### ISSUE TITLE
Compare plzip with gzip speed / size

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#1333]
http://www.nongnu.org/lzip/plzip.html

**Comment by jcushman** [comment]
@ikreymer -- 

@anastasia raised the idea of saving space by using alternate compression formats such as lzip (or .xz?) instead of gzip for warcs. Any thoughts?

A few potential issues ...

- gzip lets us play back individual records in the .warc.gz by starting decompression from a defined byte offset in the compressed file -- would need alternate compression format to support that
- in theory, less common compression formats raise more of a risk that they won't be easily readable by future users
- likewise, we might have to convert to .gz when uploading to Internet Archive or other third-party archives we want to be able to understand the underlying content

**Comment by anastasia** [comment]
Here are some preliminary findings:

If size is not our main concern but time is, we might want to stick with the .gz format but use pigz ("parallel implementation of gzip")

Using a 1.1MB warc file (time is CPU time):

**gzip** 
compress: 0m0.046s, 746KB
decompress: 0m0.014s

**pigz**
compress: 0m0.064s, 745KB (not entirely sure why it's 1KB smaller, the output is .gz)
decompress: 0m0.012s

If our main priority is size, we might want to consider pzlip

**plzip**
compress: 0m0.216s, 454KB
decompress: 0m0.046s

**lzip**
compress: 0m0.221s, 454KB
decompress: 0m0.067s

Here is a comprehensive study with a couple more compression formats that arrives at a similar conclusion:
http://vbtechsupport.com/1576/

**Comment by anastasia** [comment]
Wonder if it'd be worthwhile to run some (more extensive) tests on our production setup? I'm guessing my local environment compression testing is not exactly indicative of production-level compression speeds
