### ISSUE TITLE
Get logo and display data during registrar signup

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#1387]
In the registrar signup form, we should ask them to supply a logo and ask whether we can show their participation on the /about page.

**Comment by rebeccacremona** [comment]
Do we want to provide any help text for the logo field? (ask for png, certain dimensions, etc.) My instinct says no: with the layout of this page, we want the form to be as lightweight as possible, and adding info, even if helpful, will clutter and discourage rather than expedite. If they send us an image we can't use, we can always followup, which I gather we presently do every time.

**Comment by jcushman** [comment]
That sounds good. I think when we use the logos we're transcoding/thumbnailing them anyway.

I would whitelist to png/jpg/gif, though, both for the file picker and on the server side.

**Comment by rebeccacremona** [comment]
Perspective of the day: we don't actually prefer this on the signup form.

We talked about requesting it after the fact (say, by adding those fields to the "edit registrar" form, and advertising their presence the first time someone from that registrar logs in), but decided to hold off on that as well:  users should not be able to upload something public-facing, and we also want to rethink how we currently display logos before we ask users to go through the work of supplying them. (Registrars like seeing them, but folks feel the carousel is no longer doing it for us. We might also want to display them on contact forms.... in which case we might be okay with displaying user-uploaded content).

We'll add some stuff under a feature flag to make this easier if we decide to go through with it in the future.
