### ISSUE TITLE
Unused error views

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#1703]
Call me crazy, but I don't think these custom error views are being used. Run your local instance with DEBUG=False (requires setting ALLOWED_HOSTS = ['*'] and running ./manage.py collectstatic). Then checkout the following lines of common.py:

```
## We need custom views for server errors because otherwise Django
## doesn't send a RequestContext (meaning we don't get STATIC_ROOT).
def server_error_404(request):
    return HttpResponseNotFound(render_to_string('404.html', context_instance=RequestContext(request)))
def server_error_500(request):
    return HttpResponseServerError(render_to_string('500.html', context_instance=RequestContext(request)))
```
Try changing the 404 function: render landing.html instead, or add print statements, even delete the whole function. It appears that nothing changes: 404 still renders identically, any print statements are ineffectual, and if the function is deleted entirely, django doesn't complain.

That behavior makes me suspicious about the custom 500 function below it as well.

**Comment by jcushman** [comment]
Good call -- looks like these are being ignored because `handler404` and `handler500` are being set in perma_web/perma/urls.py instead of perma_web/urls.py.

The comment about why we want custom error views doesn't seem to be true anymore -- 404.html is still getting RequestContext even though we're not using the function -- so maybe just delete those functions and remove the lines in perma_web/perma/urls.py?

**Comment by rebeccacremona** [comment]
See https://github.com/harvard-lil/perma/pull/1731
