### ISSUE TITLE
Use a subdomain instead of a separate domain to serve archives

### ISSUE THREAD

**Issue by leonidg** [harvard-lil/perma#1913]
Users with third-party cookies disabled can't see the preview on private archives.

The snapshot from a private archive is served from perma-archives.org, while the actual view of the private archive is served from perma.cc.  Because the archive has a privacy element, it requires a cookie.  But it's a third-party cookie, which, if disabled, causes an authorization error.

An "easy" solution would be to serve from something like archives.perma.cc (which I am pretty sure should work).  The other option is to use perma.cc as a reverse proxy for perma-archives.org.

**Comment by jcushman** [comment]
The issue here is if we serve archives from archives.perma.cc, we are susceptible to session fixation: hostile archives can set cookies for .perma.cc which are indistinguishable from cookies we set ourselves, and therefore can cause viewers to be logged in as the attacker.

It's hard to put bounds on what else hostile archives could do as far as stealing user sessions, given the imperfect security models of various browsers, but session fixation is one thing attackers can definitely do that AFAIK browsers don't give us tools to prevent, so it's not appealing to even go down the road of trying to make this safe.

This isn't just us -- for example, the Django security model basically says that all bets are off if you let hostile users control subdomains of your site:

https://docs.djangoproject.com/en/1.10/ref/csrf/#csrf-limitations
https://docs.djangoproject.com/en/1.10/topics/http/sessions/#topics-session-security

That does leave the problem of handing off some sort of auth token for playback of private archives. Any thoughts about more robust ways to solve that than what we have now? As part of the difficulty level, note that IE and Safari have special limits on setting cookies in iframes:

http://www.mendoweb.be/blog/internet-explorer-safari-third-party-cookie-problem/

Also note that some potential solutions like putting the token in the URL would leak the token to a hostile archive, which may or may not be a problem ...

**Comment by leonidg** [comment]
[Sorry, didn't mean to ignore this thread...]

That's a good point about session fixation.  I certainly didn't think about that.

The "correct" answer may be [`window.postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), but unfortunately that still has [pretty lousy support](http://caniuse.com/#feat=x-doc-messaging).  The main advantage I can think of with doing that as opposed to passing a token over URL is that you could ensure that the hostile archive isn't loaded until after the message is received.  That said, if you could come up with a scheme behind the scenes to make the auth token be one-time-use, passing it over the URL shouldn't be a problem.  Something like:

1. User loads perma.cc/archive-id
2. perma.cc backend talks to perma-archives.org backend and sends a one-time-use auth token for `archive-id` and waits for an ACK before serving up the HTML/JS.
3. user's browser loads the iframe when it gets it.

This obviously requires step 2 to be carefully engineered so that if perma-archives.org is down, step 3 can still happen and show something appropriate in the iframe window.  But this doesn't seem too bad?

Obviously, I haven't looked at the codebase in forever, so I 100% guessing about what the architecture looks like.  But does that seem plausible?

**Comment by jcushman** [comment]
Yeah, both domains are served by the same app server, so the backend part of passing tokens around is simple for now. (And would be solvable even if the backend was more complicated.)

What scared me off of URL tokens is a security edge case I haven't quite worked through. The tokens aren't quite one-time-use, since they have to cover all the subrequests as well (images, JS, etc. loaded by the captured HTML). So the token has to last as long as the playback might be triggering additional resource loads -- say a minute, or five minutes to avoid weird edge cases? (Like, you're reading a long article and images load as you scroll.)

So ... you could construct a page that grabs URL tokens and send them back to you when it's replayed, allowing you to replay the page yourself for the next X minutes even if it's marked private. But ... I think that's safe? As long as there's no personal information about the capturing Perma user in the archive, and the token doesn't let you see anything except a playback of the page itself.

**Comment by leonidg** [comment]
Man, I've been out of the code-writing game for too long.  Don't know how I forgot about the fact that a website is going to make multiple requests...

Something that I should have asked earlier: how _does_ the current setup work?  I'm assuming it's actually something sort of similar?  perma.cc talks to perma-archives.org so that perma-archives.org can set an appropriate cookie that lets you load the right archive?  If that's correct, wouldn't it result in the same problem as the auth token in the URL?  Any malicious script in the archive could grab that cookie and let other people grab the archive.  Or am I totally off?

(In any case, I actually almost feel worse about the fact that the auth token (in URL, cookie, or whatever) has to have a sort of arbitrary TTL than I do about the potential security flaw.  Five minutes is a long time, but I can imagine a slow connection resulting in a weirdly half-loaded website.  Maybe that's okay.  But as far as security goes, as you said, a website capturing the auth token would only be able to use it to load the archive, and it's not clear what that actually accomplishes.)

**Comment by rebeccacremona** [comment]
We are now using a self-hosted version Webrecorder for playback of warcs; cookies for the playback of private Perma Links are now handled differently, via a series of redirects. So, if I understand correctly, this should no longer be relevant!
