### ISSUE TITLE
csrf errors are too frequent?

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#1950]
we sometimes (too frequently) receive csrf errors when loading perma.cc. why do these pop up so frequently? how often do we see them? is this a real issue?

**Comment by rebeccacremona** [comment]
I think this should be fixed by the upgrade to Django 1.10: please feel free to reopen if you still see this behavior.

"To protect against BREACH attacks, the CSRF protection mechanism now changes the form token value on every request (while keeping an invariant secret which can be used to validate the different tokens)."

https://docs.djangoproject.com/en/1.11/releases/1.10/#csrf
