### ISSUE TITLE
Washington Post images not displayed

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#2055]
https://perma.cc/5UAZ-RP87

**Comment by rebeccacremona** [comment]
Anastasia says: the image files are in the WARC, and that this happens off-and-on with a single archive: sometimes it works, and other times it doesn't, and that she THINKS they playback consistently in Electron viewer.

**Comment by anastasia** [comment]
Changed my mind, Electron viewer does not display the images that are not displayed in Perma

**Comment by rebeccacremona** [comment]
These images aren't displaying because they are using wild and crazy javascript instead of standard img behavior (or instead of srcsets, which were designed for this purpose, and which we support through extra Perma code):

example:

```
<img src="https://perma-archives.org/warc/5UAZ-RP87/https://images.washingtonpost.com/?url=https://img.washingtonpost.com/pb/resources/img/spacer.gif&amp;op=resize&amp;w=1&amp;h=1&amp;filter=nearest&amp;fmt=png" data-hi-res-src="https://perma-archives.org/warc/5UAZ-RP87/https://img.washingtonpost.com/wp-apps/imrs.php?src=https://img.washingtonpost.com/blogs/worldviews/files/2017/06/0606_GameofThrones_Foreign.jpg&amp;w=60&amp;h=60" data-low-res-src="https://perma-archives.org/warc/5UAZ-RP87/https://img.washingtonpost.com/wp-apps/imrs.php?src=https://img.washingtonpost.com/blogs/worldviews/files/2017/06/0606_GameofThrones_Foreign.jpg&amp;w=60&amp;h=60" data-threshold="60" class="photo right small-img _1-to-1 unprocessed placeholder" width="60" height="60">
```

PhantomJS not requesting data-hi-res-src or data-low-res-src, only src.  But, on playback, your browser is. So, the js that tries to load the images can't find what it needs in the warc and gets confused.

To a certain extent, this will improve as we integrate more tightly with Webrecorder, but browser mismatch will continue to be a problem.
