### ISSUE TITLE
500 response on "shared folders inside an organization" call

### ISSUE THREAD

**Issue by leonidg** [harvard-lil/perma#2115]
I am getting a 500 response on the "Get a user's shared folders inside an organization" call (`https://api.perma.cc/v1/user/organizations/1/folders/?api_key=xxx`).  I tried with both a personal account that was added to an organization and the account that was created specifically for the organization (not that there's an actual difference in the underlying object, I don't think).  In both cases, the response is the web server's HTML 500 response (the one with `<h1><p>Internal Server Error</p></h1>`), so even if I'm calling it wrong, this seems like a bug.

If it helps, the accounts I tried this with are law.annualsurvey@nyu.edu and lg2651@nyu.edu.

**Comment by leonidg** [comment]
I just realized that the "1" in the URL is probably the organization ID (if so, that should probably be documented), but it doesn't seem to help; I get the same result if I call `https://api.perma.cc/v1/user/organizations/390/folders/` (390 is the ID for "Annual Survey of American Law," an organization of which the user is a member).

**Comment by rebeccacremona** [comment]
Investigating this:

Part 1: the 500 error was, I believe, due to a missing "return" statement, fixed in https://github.com/harvard-lil/perma/commit/b7eb44292fe907e43dd1ee5160cc8d98c4224c97.

Part 2: `/organizations/:id/folders` is indeed not a route in the current perma api, even though it is documented! If you check the routes mention in the issue above, you will now get a 404. Let's definitely figure out what happened here 😄

**Comment by rebeccacremona** [comment]
The docs have been overhauled! Info on getting an organization's folders is now explained more thoroughly.

https://perma-stage.org/docs/developer#get-user-account-details
https://perma-stage.org/docs/developer#get-one-organization
https://perma-stage.org/docs/developer#view-folder-subfolders
