### ISSUE TITLE
Can we simplify caching?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#2126]
Do we really need a redis caching layer? Do we really need to cache the carousel images at all, at the application layer?

Is Cloudflare sufficient? If not, why, and can we reconfigure it to be sufficient?

**Comment by rebeccacremona** [comment]
(That is the whiniest-sounding issue ever. LOL. Not whining: merely inquisitive.)

**Comment by jcushman** [comment]
Some sort of in-memory cache is necessary for warc playback - otherwise we have database and storage hits per asset in the page.

Image caches could maybe be handled downstream. Current Cloudflare cache doesn't apply to logged in users, but maybe that's fine, or maybe we could add custom cache headers for logged-in cachable stuff.
