### ISSUE TITLE
Perma can't handle some special characters when archiving urls

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#2162]
For instance, when archiving this url
http://www.taosnews.com/stories/mobile-matanza-protects-ag-heritage-by-tying-together-local-food-systems,37460
our `link.ascii_safe_url` (which calls to werkzeug's `iri_to_uri`) returns this: http://www.taosnews.com/stories/mobile-matanza-protects-ag-heritage-by-tying-together-local-food-systems%2C37460
Which is, itself, not a functioning url.

**Comment by rebeccacremona** [comment]
Data gathering: 

This server/web app is definitely misconfigured. Commas are reserved characters, and according to everything I can find, reserved characters are supposed to be percent-encoded under all circumstances (example source: https://en.wikipedia.org/wiki/Percent-encoding). If it can't recognize that , and %2 are the same, then something is worng (maybe they have something like [this](https://serverfault.com/questions/882132/iis10-url-rewrite-2-1-double-encoding-issue) going on, but who knows.)

That being said.... 

When you put the url with the comma in it into Chrome's address bar, Chrome does NOT percent-encode the comma on your behalf. 
![image](https://user-images.githubusercontent.com/11020492/33340998-8b6e3c20-d44b-11e7-9052-7a0b280bedfb.png)

Nor does Firefox or Safari, nor python requests:
```
>>> r = requests.get('http://www.berkshireeagle.com/stories/cyberattack-spreads-in-asia,507471')
>>> r.request.url
'http://www.berkshireeagle.com/stories/cyberattack-spreads-in-asia,507471'
```

Compare that with how they handle urls with unicode in them: 
![image](https://user-images.githubusercontent.com/11020492/33341233-4cb80f5a-d44c-11e7-8248-a42280df9410.png)

```
>>> r2 = requests.get('http://www.jamalouki.net/Details/40893/نقشة-الورود-ستكسو-إطلالتك-بالكامل-في-الخريف-المقبل')
>>> r2
<Response [200]>
>>> r2.request.url
'http://www.jamalouki.net/Details/40893/%D9%86%D9%82%D8%B4%D8%A9-%D8%A7%D9%84%D9%88%D8%B1%D9%88%D8%AF-%D8%B3%D8%AA%D9%83%D8%B3%D9%88-%D8%A5%D8%B7%D9%84%D8%A7%D9%84%D8%AA%D9%83-%D8%A8%D8%A7%D9%84%D9%83%D8%A7%D9%85%D9%84-%D9%81%D9%8A-%D8%A7%D9%84%D8%AE%D8%B1%D9%8A%D9%81-%D8%A7%D9%84%D9%85%D9%82%D8%A8%D9%84'
```

With our current link.ascii_safe_url code, we can successfully capture and playback links like http://www.jamalouki.net/Details/40893/نقشة-الورود-ستكسو-إطلالتك-بالكامل-في-الخريف-المقبل. using both Chrome and PhantomJS.

If we use self.submitted_url instead of self.ascii_safe_url, we get different results depending on which browser we are using for capturing.

Using Chrome: it works just fine. 
```
[28/Nov/2017 19:48:34] "GET /warc/H5BY-UCD6/http://www.jamalouki.net/Details/40893/%D9%86%D9%82%D8%B4%D8%A9-%D8%A7%D9%84%D9%88%D8%B1%D9%88%D8%AF-%D8%B3%D8%AA%D9%83%D8%B3%D9%88-%D8%A5%D8%B7%D9%84%D8%A7%D9%84%D8%AA%D9%83-%D8%A8%D8%A7%D9%84%D9%83%D8%A7%D9%85%D9%84-%D9%81%D9%8A-%D8%A7%D9%84%D8%AE%D8%B1%D9%8A%D9%81-%D8%A7%D9%84%D9%85%D9%82%D8%A8%D9%84 HTTP/1.1" 200 58617
```
We just get a unicode problem during playback, [making the memento headers](https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/views/common.py#L253), but that's easily fixed:
```
    link_memento_headers = u'<{0}>; rel="original"; datetime="{1}",<{2}>; rel="memento"; datetime="{1}",<{3}>; rel="timegate",<{4}>; rel="timemap"; type="application/link-format"'
    response['Link'] = (link_memento_headers.format(link.ascii_safe_url, link.memento_formatted_date, link.memento, link.timegate, link.timemap)).encode('utf-8')
```

Using PhantomJS, capture succeeds, but playback fails.
```
[28/Nov/2017 19:51:48] "GET /warc/QR4G-E8XG/http://www.jamalouki.net/Details/40893/%D9%86%D9%82%D8%B4%D8%A9-%D8%A7%D9%84%D9%88%D8%B1%D9%88%D8%AF-%D8%B3%D8%AA%D9%83%D8%B3%D9%88-%D8%A5%D8%B7%D9%84%D8%A7%D9%84%D8%AA%D9%83-%D8%A8%D8%
```

That's because Chrome percent-encodes the url for us before it sends the request on through warcprox, but PhantomJS does not. So, even though phantom loads the page perfectly, and all the traffic works and is recorded, the warc gets all screwed up and is unusable, except for the screenshot:
```
Location: http://www.jamalouki.net/Details/40893/Ù†Ù‚Ø´Ø©-Ø§Ù„ÙˆØ±ÙˆØ¯-Ø³ØªÙƒØ³Ùˆ-Ø¥Ø·Ù„Ø§Ù„ØªÙƒ-Ø¨Ø§Ù„ÙƒØ§Ù…Ù„-ÙÙŠ-Ø§Ù„Ø®Ø±ÙŠÙ-Ø§Ù„Ù…Ù‚Ø¨Ù„?&???-??????-?????-???????-???????-??-??????-??????&r=1

<snip>

WARC/1.0
WARC-Type: request
WARC-Record-ID: <urn:uuid:fc60f494-8010-42fb-a367-3277adb379a3>
WARC-Date: 2017-11-28T19:51:16Z
WARC-Target-URI: http://www.jamalouki.net/Details/40893/????-??????-?????-???????-???????-??-??????-??????
WARC-Concurrent-To: <urn:uuid:d74e4c60-6d16-4900-95a6-aced4d86d1a1>
WARC-Block-Digest: sha1:70fa69ab7bfc63ab3617201665b8d06f664f3453
Content-Type: application/http;msgtype=request
Content-Length: 356

GET /Details/40893/????-??????-?????-???????-???????-??-??????-?????? HTTP/1.1
```

Here's the commit where (ascii_)safe_url gets added to the code base: it's clearly a fix for exactly this problem. https://github.com/harvard-lil/perma/commit/1e1b188675313b8c35c233b13b8889a205e723cc

Next step: deciding how we want to handle this.

**Comment by rebeccacremona** [comment]
Idea #1: we could use requests's technique for quoting URLS instead of Werkzeug's
https://github.com/requests/requests/blob/e4fc3539b43416f9e9ba6837d73b1b7392d4b242/requests/models.py#L430
```
>>> from requests.utils import requote_uri
>>> requote_uri('http://www.jamalouki.net/Details/40893/نقشة-الورود-ستكسو-إطلالتك-بالكامل-في-الخريف-المقبل')
'http://www.jamalouki.net/Details/40893/%D9%86%D9%82%D8%B4%D8%A9-%D8%A7%D9%84%D9%88%D8%B1%D9%88%D8%AF-%D8%B3%D8%AA%D9%83%D8%B3%D9%88-%D8%A5%D8%B7%D9%84%D8%A7%D9%84%D8%AA%D9%83-%D8%A8%D8%A7%D9%84%D9%83%D8%A7%D9%85%D9%84-%D9%81%D9%8A-%D8%A7%D9%84%D8%AE%D8%B1%D9%8A%D9%81-%D8%A7%D9%84%D9%85%D9%82%D8%A8%D9%84'
>>> requote_uri('http://www.berkshireeagle.com/stories/cyberattack-spreads-in-asia,507471')
'http://www.berkshireeagle.com/stories/cyberattack-spreads-in-asia,507471'
>>> 
```

**Comment by rebeccacremona** [comment]
Idea 2: we could adjust warcprox's behavior, so it doesn't try to cast to ascii https://github.com/internetarchive/warcprox/blob/master/warcprox/warcproxy.py#L337

**Comment by rebeccacremona** [comment]
Idea 3: we could do nothing, and count this as resolved once we are capturing with Firefox or Chrome in production.

**Comment by rebeccacremona** [comment]
I think idea 1 is probably best.

**Comment by rebeccacremona** [comment]
Merged in https://github.com/harvard-lil/perma/pull/2170
