### ISSUE TITLE
Add expand symbol/word to more details view in links list

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/perma#2173]

**Comment by anastasia** [comment]
<img width="896" alt="screen shot 2018-02-06 at 11 00 03 am" src="https://user-images.githubusercontent.com/1494102/35869737-d24dbd78-0b2d-11e8-9c95-fa89fba1411b.png">
something simple like this maybe?

**Comment by rebeccacremona** [comment]
This was presented and discussed at last Thursday's meeting.

1) Everybody thought the spot was great!
2) Some people were concerned about the icon: to them this suggested things could be reordered, rather than expanded. Some people suggested a plus sign with a circle (which to other people, suggested new items could be added). Some people suggested a down-facing caret that switches to an up-facing caret when expanded. @anastasia as local design expert gets to pick
3) Anything that gets triggered by hover should get triggered by focus too

**Comment by rebeccacremona** [comment]
Done!
