### ISSUE TITLE
API Docs should discuss creating archive in subfolder

### ISSUE THREAD

**Issue by dbateyko** [harvard-lil/perma#2337]
Similar to [this filed issue](https://github.com/harvard-lil/perma/issues/2117), but I didn't understand their fix.  Using the API documentation, I'm trying and failing to create an archive in an organizational subfolder. 

`
curl -H 'Content-Type: application/json' -X POST -d '{"url": "http://google.com", "title": "This is an example site", "folder": 'xx-xx-xx'}' https://api.perma.cc/v1/archives/?api_key=xx
`
Is there a good fix for this?

**Comment by rebeccacremona** [comment]
Yes! The above is almost right: just use `"folder": 54` rather than `"folder": 2-9-54`, where the numbers match your case. Or, POST to https://api.perma.cc/v1/folders/54/archives (with, then, no need to include the folder ID in the posted data).

Sounds like our API docs aren't doing the job. We'll aim to revise and polish soon! If you have particular suggestions, we'd love to hear them!

**Comment by dbateyko** [comment]
Thanks Rebecca! That's so straightforward, I can see how I overlooked that folders are integers. If you do plan to update the docs though, a brief note on how subfolders work in the folders section (in addition to the archive section) would clarify this.

**Comment by rebeccacremona** [comment]
Instructions are now included here: https://perma-stage.org/docs/developer#create-an-archive
