### ISSUE TITLE
Unable to archive minds.com properly

### ISSUE THREAD

**Issue by Serkan-devel** [harvard-lil/perma#2433]
I've tried to archive a post from minds.com which originally looks like this
![auswahl_301](https://user-images.githubusercontent.com/16866642/43687789-17c84814-98dc-11e8-9f67-b672d8f8f375.png)
(Source:https://www.minds.com/media/872531951251099648)

But not everything gets archived, only the navbar shows up
![auswahl_300](https://user-images.githubusercontent.com/16866642/43687801-56e63556-98dc-11e8-8641-2383876d37ec.png)
(Source: http://perma.cc/CL3E-WYZC)

The root webpage of minds.com/ also looks the same http://perma.cc/R6B5-7GXD

Minds is an open source social network, which is how one can see that it uses AngularJS on the frontend https://github.com/minds/front

Could it be resolved with reference to to minds' source?

**Comment by rebeccacremona** [comment]
Interesting.

So there are a couple things going on here. 

Easy to diagnose: the screenshots are coming out poorly because PhantomJS, the browser we use to capture websites, is overtaxed by minds.com.

Hard to diagnose: during playback, the javascript for minds.com is erroring out, reliably, but in different places depending on which page. It's hard to say exactly why.... But, it looks like you can get good captures of minds.com using WebRecorder (https://webrecorder.io). Perma and WebRecorder plan to work more closely together in the near future, which hopefully will include WebRecorder's superior ability to capture these pages!

**Comment by Serkan-devel** [comment]
I thought you were making your own transition from phatomjs to selenium as described with [this comment](https://github.com/harvard-lil/perma/issues/2429#issuecomment-410329703). Will that still happen, or will there be a difference between both projects?

**Comment by rebeccacremona** [comment]
Not quite: as mentioned there, the project to switch Perma from PhantomJS to headless Firefox or headless Chrome is on hold, because working more closely with WebRecorder will make the effort unnecessary/redundant. However, if that work ends up taking longer than expected, we would definitely consider making another push this autumn to move Perma as-is from PhantomJS to headless Firefox or headless Chrome.

**Comment by Serkan-devel** [comment]
How long will that take?
I'm trying to capture the events when the minds token gets released https://www.minds.com/token
This is most likely the first social network, incorporating a crypto currency to the framework

**Comment by rebeccacremona** [comment]
We're hoping for some time this autumn, but work is still in the early stages.

In the meantime, I'd suggest using WebRecorder for high-fidelity captures of minds.com. If you need a Perma Link, you can upload a screenshot to Perma: submit the capture form blank, without specifying a URL, and then click "upload your own archive"
