### ISSUE TITLE
inoperable URI-G and URI-T values in HTTP response

### ISSUE THREAD

**Issue by phonedude** [harvard-lil/perma#2682]
I noticed this a while ago but I'm just now getting to opening an issue.  Taking the URLs for the TimeMap (URI-T) and TimeGate (URI-G) from this response:

$ curl -I https://perma.cc/7TVJ-PMF7
HTTP/1.1 200 OK
Date: Mon, 11 Nov 2019 23:00:45 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=dba4cf8d2137ef05dc6f8f762ebf1debd1573513245; expires=Tue, 10-Nov-20 23:00:45 GMT; path=/; domain=.perma.cc; HttpOnly; Secure
Memento-Datetime: Sun, 29 Apr 2018 18:24:10 GMT
Vary: Cookie, Host
Link: <https://twitter.com/zittrain/status/990648288918626304>; rel="original"; datetime="Sun, 29 Apr 2018 18:24:10 GMT",<https://perma.cc/7TVJ-PMF7>; rel="memento"; datetime="Sun, 29 Apr 2018 18:24:10 GMT",<https://wr.perma-archives.org/warc/timegate/https://twitter.com/zittrain/status/990648288918626304>; rel="timegate",<https://wr.perma-archives.org/warc/timemap/*/https://twitter.com/zittrain/status/990648288918626304>; rel="timemap"; type="application/link-format"
Cache-Control: public, max-age=3600
Strict-Transport-Security: max-age=15768000
CF-Cache-Status: MISS
Expires: Tue, 12 Nov 2019 00:00:45 GMT
Accept-Ranges: bytes
Set-Cookie: sessionid=f8n10zmqehphoeat8zir2jw4rej12nbw; expires=Mon, 25-Nov-2019 23:00:45 GMT; HttpOnly; Max-Age=1209600; Path=/; Secure
Set-Cookie: __cflb=1582820817; Secure; path=/; expires=Tue, 12-Nov-19 22:00:45 GMT; HttpOnly
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5343e255afbec084-ORF

I get 303'd to an error page:

$ curl -I https://wr.perma-archives.org/warc/timemap/*/https://twitter.com/zittrain/status/990648288918626304
HTTP/1.1 303 See Other
Date: Mon, 11 Nov 2019 23:00:57 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d5d86eded8de4dc56fe54c59a25ce4f901573513256; expires=Tue, 10-Nov-20 23:00:56 GMT; path=/; domain=.perma-archives.org; HttpOnly; Secure
Location: https://perma.cc/archive-error?status=404&error=no_such_user
X-Proxy-Cache: BYPASS
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5343e2a01d9ac06b-ORF

$ curl -I https://wr.perma-archives.org/warc/timegate/https://twitter.com/zittrain/status/990648288918626304
HTTP/1.1 303 See Other
Date: Mon, 11 Nov 2019 23:01:08 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d2c2b6d19f5f018368b184a03ecc1ed9a1573513267; expires=Tue, 10-Nov-20 23:01:07 GMT; path=/; domain=.perma-archives.org; HttpOnly; Secure
Location: https://perma.cc/archive-error?status=404&error=no_such_user
X-Proxy-Cache: BYPASS
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5343e2e4e9aec070-ORF

I get the same behavior when opening that URL in a regular browser.  Perhaps "wr.perma-archives.org" is not supposed to be exposed?  See also:

$ curl -IL https://wr.perma-archives.org/
HTTP/1.1 303 See Other
Date: Mon, 11 Nov 2019 23:11:07 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=d9886eff59e1ac985f0ad94c0061abdda1573513867; expires=Tue, 10-Nov-20 23:11:07 GMT; path=/; domain=.perma-archives.org; HttpOnly; Secure
Location: https://wr.perma-archives.org:8443/
X-Proxy-Cache: BYPASS
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5343f186ee42c066-ORF

HTTP/1.1 404 Not Found
Date: Mon, 11 Nov 2019 23:11:09 GMT
Content-Type: text/html
Connection: keep-alive
Set-Cookie: __cfduid=d74d4ab17832376afcf7dc3848e357d7c1573513868; expires=Tue, 10-Nov-20 23:11:08 GMT; path=/; domain=.perma-archives.org; HttpOnly; Secure
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5343f1911991c06b-ORF

**Comment by phonedude** [comment]
FYI: still happening as of today (2019-11-29).

**Comment by rebeccacremona** [comment]
Hello @phonedude! Many thanks for filing this, as well as https://github.com/harvard-lil/perma/issues/2471, and sincere apologies for my long radio silence on the topic (...and others...)

In the summer of 2019, Perma began experimenting with a new playback mechanism for our warcs, migrating from a dated, custom pywb integration to a more-robust Webrecorder-based approach. We knew that the new strategy broke our memento support, but due to outside concerns, we were only just now able to fix it.

Within the next few days, we will be deploying completely reimplemented support for timegates, timemaps, and memento-related headers on Perma Link playbacks (https://github.com/harvard-lil/perma/pull/2699)

Timemaps will, after the deployment, be available at:
```
https://perma.cc/timemap/link/<url>
https://perma.cc/timemap/json/<url>
https://perma.cc/timemap/html/<ulr>
```
and timegates will be available at:
```
https://perma.cc/timegate/link/<ulr>
```

We'll redirect (301) from the old routes to the new routes.

Only publicly-available Perma Links will be listed in timemaps or redirected to via timegates. Users should no longer uselessly get redirected to private, deleted, or potentially transient (e.g. less than 24-hours old, and still subject to user deletion) Perma Links. If, via a non-standard mechanism, a user encounters a playback of a Perma Link they would not be able to discover via a timemap or a timegate, that playback will NOT include headers like `link` or `memento-datetime` in the response, to avoid confusion.

As per the discussion in https://github.com/harvard-lil/perma/issues/2471, all available timemaps will be served and listed with an appropriate `content-type`

Finally, we had to make a design decision about which URLs to expose via timemap/timegate. You may recall that Perma makes a full recording of a requested URL and its assets (css, js, images, media, etc.) each time a user makes a Perma Link, and we store each recording in its own warc. Our current playback setup only permits users to request playback of the full Perma Link (e.g. `https://perma.cc/B2ND-UEGX`, an archive of lil.law.harvard.edu); you cannot independently request playback of a single asset collected during the recording, like `https://lil.law.harvard.edu/assets/css/main.css`. Accordingly, we will only be exposing timemaps and timegates for top-level captured URLs, not for every resource in our warcs. We may be able readdress this in the future, if we can implement support for playback of individual assets within a Perma Link.

Not live yet:

```
curl -I  http://perma.test:8000/7LVC-6K3F
HTTP/1.0 200 OK
Date: Mon, 03 Feb 2020 22:47:51 GMT
Server: WSGIServer/0.2 CPython/3.7.3
Content-Type: text/html; charset=utf-8
Memento-Datetime: Wed, 28 Aug 2019 17:59:50 GMT
Link: <http://example.com?foo=bar>; rel=original, <http://perma.test:8000/timegate/http://example.com?foo=bar>; rel=timegate, <http://perma.test:8000/timemap/link/http://example.com?foo=bar>; rel=timemap; type=application/link-format, <http://perma.test:8000/timemap/json/http://example.com?foo=bar>; rel=timemap; type=application/json, <http://perma.test:8000/timemap/html/http://example.com?foo=bar>; rel=timemap; type=text/html, <http://perma.test:8000/7LVC-6K3F>; rel=memento; datetime="Wed, 28 Aug 2019 17:59:50 GMT"
```

```
LSC02VK05ZHTDG:perma rcremona$ curl -I  http://perma.test:8000/timemap/json/example.com
HTTP/1.0 200 OK
Date: Mon, 03 Feb 2020 22:49:41 GMT
Server: WSGIServer/0.2 CPython/3.7.3
Content-Type: application/json
X-Memento-Count: 14
Content-Length: 1769
Vary: Host

HLSC02VK05ZHTDG:perma rcremona$ curl  http://perma.test:8000/timemap/json/example.com
{"self": "http://perma.test:8000/timemap/json/example.com", "original_uri": "example.com", "timegate_uri": "http://perma.test:8000/timegate/example.com", "timemap_uri": {"json_format": "http://perma.test:8000/timemap/json/example.com", "link_format": "http://perma.test:8000/timemap/link/example.com", "html_format": "http://perma.test:8000/timemap/html/example.com"}, "mementos": {"first": {"uri": "http://perma.test:8000/ZYY3-HQQW", "datetime": "2019-06-11T14:10:30.290Z"}, "last": {"uri": "http://perma.test:8000/8L4S-WN9Q", "datetime": "2020-01-17T19:27:14.348Z"}, "list": [{"uri": "http://perma.test:8000/ZYY3-HQQW", "datetime": "2019-06-11T14:10:30.290Z"}, {"uri": "http://perma.test:8000/L2HV-H8FR", "datetime": "2019-06-17T17:49:07.809Z"}, {"uri": "http://perma.test:8000/A4LL-JW7S", "datetime": "2019-06-17T17:54:12.782Z"}, {"uri": "http://perma.test:8000/HNU4-GVHB", "datetime": "2019-06-17T17:56:39.347Z"}, {"uri": "http://perma.test:8000/ACV8-CNKJ", "datetime": "2019-06-17T17:59:25.300Z"}, {"uri": "http://perma.test:8000/459Z-ETTP", "datetime": "2019-06-17T18:01:47.908Z"}, {"uri": "http://perma.test:8000/2APU-XY5Q", "datetime": "2019-06-17T18:03:03.447Z"}, {"uri": "http://perma.test:8000/AE77-AL4F", "datetime": "2019-07-25T18:33:20.692Z"}, {"uri": "http://perma.test:8000/4A93-PM6S", "datetime": "2019-07-25T18:36:04.193Z"}, {"uri": "http://perma.test:8000/S4AM-L33A", "datetime": "2019-07-26T13:15:16.389Z"}, {"uri": "http://perma.test:8000/2HT3-72KQ", "datetime": "2019-07-26T13:16:10.710Z"}, {"uri": "http://perma.test:8000/CKZ7-JSAJ", "datetime": "2019-10-23T18:49:47.266Z"}, {"uri": "http://perma.test:8000/35D3-MTVE", "datetime": "2020-01-17T16:49:39.157Z"}, {"uri": "http://perma.test:8000/8L4S-WN9Q", "datetime": "2020-01-17T19:27:14.348Z"}]}
```


```
HLSC02VK05ZHTDG:perma rcremona$ curl  http://perma.test:8000/timemap/link/example.com
<example.com>; rel=original,
<http://perma.test:8000/timegate/example.com>; rel=timegate,
<http://perma.test:8000/timemap/link/example.com>; rel=timemap; type=application/link-format,
<http://perma.test:8000/timemap/json/example.com>; rel=timemap; type=application/json,
<http://perma.test:8000/timemap/html/example.com>; rel=timemap; type=text/html,
<http://perma.test:8000/ZYY3-HQQW>; rel=memento; datetime="Tue, 11 Jun 2019 14:10:30 GMT",
<http://perma.test:8000/L2HV-H8FR>; rel=memento; datetime="Mon, 17 Jun 2019 17:49:07 GMT",
<http://perma.test:8000/A4LL-JW7S>; rel=memento; datetime="Mon, 17 Jun 2019 17:54:12 GMT",
<http://perma.test:8000/HNU4-GVHB>; rel=memento; datetime="Mon, 17 Jun 2019 17:56:39 GMT",
<http://perma.test:8000/ACV8-CNKJ>; rel=memento; datetime="Mon, 17 Jun 2019 17:59:25 GMT",
<http://perma.test:8000/459Z-ETTP>; rel=memento; datetime="Mon, 17 Jun 2019 18:01:47 GMT",
<http://perma.test:8000/2APU-XY5Q>; rel=memento; datetime="Mon, 17 Jun 2019 18:03:03 GMT",
<http://perma.test:8000/AE77-AL4F>; rel=memento; datetime="Thu, 25 Jul 2019 18:33:20 GMT",
<http://perma.test:8000/4A93-PM6S>; rel=memento; datetime="Thu, 25 Jul 2019 18:36:04 GMT",
<http://perma.test:8000/S4AM-L33A>; rel=memento; datetime="Fri, 26 Jul 2019 13:15:16 GMT",
<http://perma.test:8000/2HT3-72KQ>; rel=memento; datetime="Fri, 26 Jul 2019 13:16:10 GMT",
<http://perma.test:8000/CKZ7-JSAJ>; rel=memento; datetime="Wed, 23 Oct 2019 18:49:47 GMT",
<http://perma.test:8000/35D3-MTVE>; rel=memento; datetime="Fri, 17 Jan 2020 16:49:39 GMT",
<http://perma.test:8000/8L4S-WN9Q>; rel=memento; datetime="Fri, 17 Jan 2020 19:27:14 GMT",
```

etc.

I'm hopeful this whips us into shape.

**Comment by rebeccacremona** [comment]
Fixed in https://github.com/harvard-lil/perma/pull/2699
