### ISSUE TITLE
"Could not load URL" error

### ISSUE THREAD

**Issue by arderyp** [harvard-lil/perma#2924]
I cannot archive the url below via the web GUI or the API, both of which produce a "Could not load URL" error

https://www.census.gov/content/dam/Census/library/visualizations/time-series/demo/families-and-households/hh-4.pdf

P.S. this url was successfully archived by someone else on February 25 2018:  [https://perma.cc/9NFN-YT93](https://perma.cc/9NFN-YT93)

**Comment by rebeccacremona** [comment]
That URL is, as of today, extremely slow to respond when accessed via python:
```
>>> import requests
>>> import time
>>> time.time(); requests.get(url); time.time()
>>> time.time(); requests.get(url); time.time()
1621356814.2842953
<Response [200]>
1621356874.8055038
>>> 1621356874.8055038 - 1621356814.2842953
60.52120852470398
```
Perma has a timeout of 45s.

This appears to be because the PDF is served from a CDN cache when accessed from a browser, but not when accessed via python: I see the following headers in a browser, but not in `response.headers`.
```
server-timing | cdn-cache; desc=HIT
server-timing | edge; dur=2
```
![image](https://user-images.githubusercontent.com/11020492/118693671-48acc300-b7d9-11eb-8fc5-54fa860d4709.png)

I can explore and see if I can work out what a person needs to do, in order to get the quick, cached copy from the CDN rather than wait over a minute for what seems to be a freshly-generated PDF. 

But, I wouldn't assume I'll have luck, or that I'll be able to implement that change across the board for Perma: when tweaking the process to work around one site's quirk, it often cause us to get newly stuck on some other site's quirk. But I'll see what I can do!

In the meantime, one of our team members will respond to your email with suggestions about how to proceed.

**Comment by arderyp** [comment]
Very interesting, thanks for doing the detective work @rebeccacremona!

Since there is a perfectly good perma copy out there (the one I linked from 2018), I wonder if there's some way to copy that copy so that I can store my own copy in my own account folder.

**Comment by rebeccacremona** [comment]
@arderyp! I did not change a thing: today, census.gov returns that PDF speedily straight from the server, not just from its CDN. Behold: https://perma.cc/M8QS-26JS.

I can transfer that Perma Link to a folder in your account, if you like, or you can create a new one yourself.

I did some more digging: it looks like their "send this visitor to the CDN or not?" logic considers at least the IP address you are visiting from in addition to user agent.
`response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0'})` consistently gets the CDN-cached response if requested transparently from my home IP address but consistently gets the freshly-generated response via my AWS-hosted VPN. 

I don't think there's anything useful I'll be able to extract from pulling further on this thread, so I'm going to close this ticket, but feel free to re-open if the page starts acting up again.

**Comment by arderyp** [comment]
thanks @rebeccacremona!  I went ahead and created my own capture manually in the appropriate folder.  Thanks for the helpful debugging/investigation!
