### ISSUE TITLE
Website loads fine in browser, but perma cannot capture it

### ISSUE THREAD

**Issue by mustard123** [harvard-lil/perma#2967]
- First, our [website](https://rwi.app/iurisprudentia/de/huber/documents/static/508509/pages/2?zoom=0.7227069351230426) loads fine in the browser, but in perma the console output in the dev tools shows a syntax error and an unexpected close tag https://perma.cc/4UQ3-QC65

![image](https://user-images.githubusercontent.com/14769359/131821986-be2f760d-6738-4a44-b389-4d85e0fbc4dd.png)

- Second, the screenshot feature on perma.cc in my case shows only shows our loading spinner https://perma.cc/4UQ3-QC65?type=image
Does perma wait for javascript to load? Is there a way to delay the screenshot capture a few seconds until everything is loaded?

Does anybody have an idea why perma is not able to capture the site?
Kind regards

**Comment by rebeccacremona** [comment]
Thanks for your report!

Experimenting locally, I can confirm that this is entirely about speed: 
- Perma [waits for `onload`](https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/tasks.py#L1332)
- Then, we parse the loaded HTML and make sure capture any [tricky assets](https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/tasks.py#L1354), like all the images in a srcset
- Finally, we look to see if the browser is still making network requests, for instance, making AJAX requests, and we [wait up to 45s](https://github.com/harvard-lil/perma/blob/develop/perma_web/perma/tasks.py#L1363) for those requests to complete.

It looks like your javascript takes a while to make its requests: it hasn't made (all of) them yet, when we get to the code that checks for pending network requests. If I force Perma to sleep for at least 2s, before #L1363 and checking for pending network requests, then we capture your page in its entirety.

This is tricky. We don't want to put in a 2 second delay for every Perma capture. We can consider adding custom handling, just for `https://rwi.app`, that will add a 2 second delay for your site only. You might be able to refactor your javascript so that it runs more efficiently, making its AJAX requests sooner. (When loading directly in the browser, I see multiple console errors that report `Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/de/huber/documents/static/508509/pages/2?zoom=0.52".`, so it sounds like maybe this JS is a little wonky?)

I'll look into whether a custom 2s delay for `https://rwi.app` is feasible.

All best,
Rebecca

**Comment by mustard123** [comment]
Dear Rebecca

Thank you very much for looking into this issue and your reply. We appreciate it a lot. I agree, some of the Javascript  probably needs some reworking, in fact we are still in the process of development. Nevertheless, we would be very grateful if it were possible to just add the delay for our domain, so that our scholars can already start using Perma for their work, while we are still fine tuning the website.

Kind regards

**Comment by rebeccacremona** [comment]
No problem!

We just deployed a custom 2s delay for your domain, and it seems to be working: https://perma.cc/X76V-G5DF. If your scholars see any more pages that aren't working, just let us know.

Best of luck with your project; it's very interesting!
