### ISSUE TITLE
Consider client-side replay data lifetimes.

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/perma#3038]
Wabac.js (and replayweb.page) throw a bunch of information into indexeddb for storage and replay. This has a few implications:

 - We may be able to avoid some web requests if someone already has needed info cached.
 - We may run into issues with errors or eviction if we bump up against the built-in storage limits (https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#storage_limits). Browsers have /some/ sensible defaults, but we may end up using proportionally more indexeddb space than our fair share, and run into trouble. 
 - We can consider a, hopefully smarter, eviction policy if it's necessary: https://github.com/webrecorder/wabac.js/blob/664a21099a82663066c67f13081c059ded68bcaf/src/archivedb.js#L76 lets us clear out the indexeddb data for a page pretty easily.
 - We can make some modifications (maybe just in the form of documentation) to replay-web to not use indexeddb, but an in-memory store. 
 - We may want to try to detect if this is actually a problem, and alert on it. Maybe this could be bundled up with some diagnostics about requested items not in an archive?

**Comment by rebeccacremona** [comment]
Our current strategy is to clear things out as much as possible, by sending [`Clear-Site-Data: '"cache", "storage"'`](https://github.com/harvard-lil/perma/blob/356567698d29d027c9885cee58fad7696b36ecf5/perma_web/replay/views.py#L35) each time. (We were clearing cookies too, but it turns out that [logs you out of Chrome](https://github.com/harvard-lil/perma/pull/3134)...)

We also attempt some cleanup if you GET replay.perma.cc from [outside an iframe](https://github.com/harvard-lil/perma/blob/356567698d29d027c9885cee58fad7696b36ecf5/perma_web/replay/templates/iframe.html#L188-L240); we probably want to add some cookie cleanup there.

We are considering trying to add some similar cleanup to the Perma logout process. (It would be safe to add `Clear-Site-Data: "cookies"` there, at least)

**Comment by matteocargnelutti** [comment]
Closing in favor of #3143 (cross-referencing)
