### ISSUE TITLE
login on chrome without the new shitty extension button doesn't work

### ISSUE THREAD

**Issue by tvnewsrtp** [harvard-lil/perma#3110]
Login on Chrome, Kinza and other similar browser with chrome://flags/#extensions-toolbar-menu support doesn't work. Example Chrome 74.0.3729.131

**Comment by matteocargnelutti** [comment]
Hi @tvnewsrtp 

We're focusing our effort on supporting the latest version(s) of the main browser engines.

We unfortunately cannot investigate potential issues with browsers which are no longer supported by their vendor. 

Chrome 74.0.3729.131 was released in April / May 2019 and [many security vulnerabilities have since been discovered and patched on this software](https://www.cvedetails.com/product/15031/Google-Chrome.html?vendor_id=1224). 

Best,
