### ISSUE TITLE
Cache Perma's playbacks?

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/perma#3142]
We currently go right to Django and S3 every time we need a playback or a warcs: no caching at the Cloudflare level; no usage of AWS Cloudfront.

Are we able to add caching, without messing things up (private playbacks remain private; cached pre-signed URLs don't expire before the cache does; when people toggle from public-to-private or back, things work; when people upload a replacement, the old playback is evicted, etc.)?

If we are able to, is it worth it: will we save a lot of money; will we use fewer resources (or more, because CDNs make lots of copies)?

**Comment by matteocargnelutti** [comment]
**Update:** 
@rebeccacremona, @bensteinberg and I discussed this issue today, in light of the deployment of #3143.

Our current setup uses S3 directly, and it is a bit unclear to us what the cost implications of having `<replay-web-page>` use range requests for everything _(via `noCache`)_  are going to be. 

There's a sense that, since it only pulls what it needs from the archive, it might reduce our total bandwidth usage. But we are not sure how S3 handles many small range requests vs one full request, in particular in terms of caching and billing. 

We have decided to experiment with the current setup _"as is"_ for the next 24-48 hours and monitor closely. 

**After that:** 
- **If impact is mostly negative on cost / performance:** we would pull back the `noCache` attribute immediately.
- **If impact is positive / neutral / minimally negative:** we are likely going to leave it _"as is"_ until we figure out a viable caching solution. 

**Caching solutions discussed:**
- Cloudflare is already partially setup on Perma and could be our go to, but doesn't spark joy as it [seems to be rounding the entire file when proxying and caching range requests](https://kevincox.ca/2021/06/04/http-range-caching/), which is inefficient.
- We could setup [another CDN-based proxy + caching solution](https://kevincox.ca/2021/06/04/http-range-caching/#what-are-cdns-doing)
- We could also set up our own self-hosted NGINX proxying / caching server for this purpose, which would allow us to fine tune a _"Slice-by-slice"_ caching approach for range requests (See: [`warc-embed`](https://github.com/matteocargnelutti/warc-embed) experiment).

**Comment by matteocargnelutti** [comment]
**Update after a few weeks of monitoring:** Our S3 usage did increase significantly, but within a reasonable range. We should therefore indeed consider adding a caching layer between S3 and `<replay-web-page>` in the near future, although there is no sense of urgency.

**Comment by mdellabitta** [comment]
It looks like Cloudfront does cache range requests.
