### ISSUE TITLE
Case-insensitive email addresses

### ISSUE THREAD

**Issue by matteocargnelutti** [harvard-lil/perma#3152]
As reported by @clare-stanton: Some of our users are running into issues because email addresses are considered case sensitive during sign-up / sign-in.

- [x] Figure out if the entire email address, or just the part before `@` should be case insensitive
- [x] See how many existing users would be impacted by proposed fix _(and how)_
- [x] Choose our preferred solution: see this [list of decisions to be made](https://docs.google.com/document/d/10mZ2e2evg-A5H-Jdv4FUg7DITqw-nxoWyiEv6x7lbNU/edit#heading=h.gqw169l0mpvz)
- [x] Apply the fix and remediate edge cases: [project board](https://github.com/orgs/harvard-lil/projects/11/views/1)

---

**Resources:**
- [Design Doc](https://docs.google.com/document/d/10mZ2e2evg-A5H-Jdv4FUg7DITqw-nxoWyiEv6x7lbNU/edit#)
- @lizadaly's work and thoughts on fixing a similar problem on H2O: https://github.com/harvard-lil/h2o/pull/1592

**Comment by kilbergr** [comment]
I found this blog post referencing RFCs around case sensitivity in email: https://verifalia.com/help/email-validations/are-email-addresses-case-sensitive. It says that domains are not case-sensitive, which would be my instinct. Regarding the username, it says that though they can be case-sensitive, it's rare that they are. I have found other articles citing the same RFC5321 (https://datatracker.ietf.org/doc/html/rfc5321) confirming that they can be case sensitive. I wonder how commonly it's an issue though. The problem is that people are putting in MYUSER@dogs.cats and myuser@dogs.cats and they're being treated as two separate users, right? Or is it you're getting myuser@dog.CATS and myuser@Dog.Cats? Or is it both?

**Comment by matteocargnelutti** [comment]
@kilbergr Main issue is the former, as [Django follows said RFC](https://django-improved-user.readthedocs.io/en/stable/email_warning.html), in `EmailField` and `normalize_email()`.

Another argument in favor of considering usernames as case sensitive _(or at least saving them that way)_, besides the fact that it is the most "RFC compliant" thing to do, is that it sometimes makes sense to save how users prefer to see their email displayed _(ie: `PersonName@domain.ext` being arguably easier to read than `personname@domain.ext`)_.

**That said:** I'm working on a very first attempt at tackling this issue, and I'm leaning towards _"let's have all emails lower case moving forward"_, which comes with its own set of challenges. 
PR / discussion to come, I'll make sure to @ you there 😄 .

Cheers.
