### ISSUE TITLE
Take a pass at UI/UX of bookmarklet

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#457]
The bookmarklet works great. Let's nail down the UI/UX. Details in commit, https://github.com/harvard-lil/perma/commit/5c216fd2f7d61d57fa137070fe81940863bf99b1

How do we best share it with users. Is it on the create page? Is it there until they drag it or select a "don't show me this message again"  panel?

Do we put it in a separate tools panel? Probably in the FAQ too?

**Comment by bensteinberg** [comment]
See also https://github.com/harvard-lil/perma/issues/998

**Comment by rebeccacremona** [comment]
Observation: if you use the bookmarket while logged out, the url gets lost in the redirect from the login form because the its url-encoded. Taking a pass at fixing that first. 

Doesn't work: https://perma.cc/login?next=/manage/create%3Fv%3D1%26url%3Dhttps%253A%252F%252Fgithub.com%252Fharvard-lil%252Fperma%252Fissues%252F457

Works:  https://perma.cc/login?next=/manage/create?url=https://github.com/harvard-lil/perma/issues/457

**Comment by rebeccacremona** [comment]
See <a href="https://github.com/harvard-lil/perma/commit/9bf0a8d50539f23e175d7047452c2fb2042da973">9bf0a8d</a> re: loggin in.

**Comment by rebeccacremona** [comment]
See also #1250

**Comment by rebeccacremona** [comment]
See also #1279

**Comment by rebeccacremona** [comment]
Per Matt's above, """maybe put a note below the create box telling the user "The bookmarklet in the Tools section might be of interest to you" (until the[y] click a "Got it. Don't show me again" box""":

- Let's not display if a user has arrived at the page via the bookmarklet or an extension
- Let's store "don't show me again" in a long-lived cookie, rather than in the DB, so people are reminded periodically, or if they log in on a new device.

Does that sound right?

**Comment by rebeccacremona** [comment]
https://github.com/harvard-lil/perma/pull/1696

This plus the other related commits referenced above probably count as a first pass: marking this as closed. Will open a separate issue for making a Safari extension, and another about verifying the extensions work well on mobile phones.
