### ISSUE TITLE
Can't assign existing users to vesting organizations

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#758]
Tried to upgrade an existing user to vesting account status. Got HTTP 500 error screen when clicked "Add to Vesting Organization."

It should allow you to find a general user by email address and then upgrade that person and assign to a vesting org.

**Comment by jcushman** [comment]
I just stumbled across this bug as well.

The issue is that adding existing users to vesting orgs and registrars through the dashboard throws an error, because when we try to send an email to the upgraded user, the email refers to a view named `user_management_manage_account` that no longer exists.

There are some other references to `user_management_manage_account` scattered around the code as well. Seems like a loose end left over from the reorg of the dashboard pages. Maybe this one's for Annie?

**Comment by abziegler** [comment]
Can we up the priority on this? Got an inquiry today  from a library that needs to be able do this.

**Comment by jcushman** [comment]
Note that the admin console approach should work now, if you want to help them out in the meantime. To make a regular user a vesting user or registrar, you can:

(1) go to edit their entry in the Users section of the admin console
(2) remove the "user" group
(3) add the "registrar_user" or "vesting_user" group
(4) select the appropriate vesting org or registrar
(5) click "save".
 
Here's a picture:

![screen shot 2015-02-03 at 5 01 24 pm](https://cloud.githubusercontent.com/assets/376272/6030587/8d3055f8-abc6-11e4-95af-7238e8b71308.png)
