### ISSUE TITLE
Convert archived PDFs to PDF/A

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/perma#764]
When we Perma a PDF, we should save a copy in PDF/A format, which is designed for long-term archival. PDFBox sounds promising:

http://unix.stackexchange.com/questions/79516/converting-pdf-to-pdf-a

**Comment by rebeccacremona** [comment]
Tentatively closing because previous experience suggests this is quite difficult and automated conversion not infrequently noiselessly corrupts the results, especially when the necessary fonts are unavailable on the system doing the conversion. Tech may have improved since; I suspect this will always be a hard problem.
