### ISSUE TITLE
Polling doesn't work on single link page

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#785]
The spinner never stops spinning. It looks like a same-origin issue. We're doing a GET to the API for perma-stage, but I get a 301 to dashboard.perma-stage. @jcushman, any advice on how best to resolve this?

**Comment by jcushman** [comment]
@leppert , can we get your thoughts as well?

The issue is that we want the single link page to do a (logged-in) API request from perma.cc/ABCD to dashboard.perma.cc/api/v1/archives/ABCD to update the status of currently-archiving links (the little spinner in the archive tabs). We do this across domains because perma.cc could in principle be served by a mirror run by a third party, and we want the API request going back to the source. The request is blocked by the same-origin policy. 

This will work if we set the Access-Control-Allow-Origin header on API responses to dashboard.perma.cc, to allow requests from plain perma.cc. The risk is that we open up some sort of XSS security hole.

There's not a risk from evil user content (e.g., malicious JS in an archived web page), because we serve all user content from another domain (user-content.perma.cc).

There *could* be a risk from an evil mirror -- say, a third-party mirror gets hacked and starts serving JS at perma.cc that uses the API to control user accounts. (Mirrors are trusted in general, but we don't want it to be a huge problem if they're compromised.) There could also be some more direct XSS risk I'm not thinking of?

Simple solutions:

(1) Set the Access-Control-Allow-Origin header just for /archives/ GET requests, meaning an XSS hole won't compromise too much.
(2) Set the Access-Control-Allow-Origin header just for /public/archives/ (which makes sense anyway), and open up that endpoint to include non-vested links.
(3) Expose some non-API endpoint for mirrors to do this status check.

 Thoughts?

**Comment by leppert** [comment]
If I'm reading this correctly, JSONP is also an option, though I believe it depends on browser configuration as to whether or not the session / cookies are sent with the request.

To be clear, this needs to be logged-in because of the restrictions we've put around archive access and visibility, is that correct? What sort of access control do we have around the single link page itself?

**Comment by jcushman** [comment]
The access-control line at the moment is that the single link page is visible to everyone, but non-vested links don't appear in bulk data access (API, memento, etc.). The idea is that you *can* put a bunch of non-vested links in a manuscript and send it to an editor to view, but you *can't* (trivially) scrape all the non-vested links to see what people are archiving. My option #2 would be to relax that limit and let non-vested links show in the API, but I'm leaning against that one.

For whatever reason JSONP doesn't seem to be defeating the cross-origin protection, at least in Chrome. Here's a request in the console in my local env:

```
$.ajax({
url: "http://dashboard.perma.dev:8000/api/v1/archives/6NUK-CNKTT/",
dataType: "jsonp",
data: {}
});
```

Response:

```
6NUK-CNKT:1 XMLHttpRequest cannot load http://dashboard.perma.dev:8000/api/v1/archives/6NUK-CNKTT/?callback=jQuery19107420200009364635_1423334181222&_=1423334181395. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://perma.dev:8000' is therefore not allowed access.
```

That could just be that I'm misusing jQuery or something. But it makes sense to me that this shouldn't work -- otherwise, what's stopping any site you visit from reading your login details at /api/v1/user/ ?

I guess the real question is, assuming it doesn't work now, do we want the /archives/ view at least to work from plain perma.cc? (Or if it does work now and I'm just making a mistake, do we want to disable it?)

**Comment by leppert** [comment]
Re: JSONP -- huh, I believe that's changed. The whole pitch with JSONP, originally, was that it wasn't subject to origin restrictions.

Opening up the API makes the most sense to me, especially since we're not using sequential IDs. Seems to me what we're really talking about are data format restrictions rather than access control. If a malicious user wants to step through a bunch of archive IDs, they can just as well scrape the HTML. I'm not sure that's sufficiently difficult to make a case for withholding an API endpoint.

**Comment by jcushman** [comment]
> The whole pitch with JSONP, originally, was that it wasn't subject to origin restrictions.

I think the deal is you have to opt in by sending back your JSON with a "text/javascript" content type, so the browser treats it as a normal third party script. Sounds like Tastypie has that disabled by default to avoid surprise XSS: http://django-tastypie.readthedocs.org/en/latest/serialization.html

> If a malicious user wants to step through a bunch of archive IDs, they can just as well scrape the HTML.

So first of all, I don't think scraping the HTML is that easy right now. Our keys are 40-bit non-sequential, which is about 1 trillion keys -- you'd have to check 1000 keys a second for 30 years to exhaust it, which is probably optimistic for how fast you could check at this point without breaking stuff.

But you're totally right that it's not a huge keyspace either -- if our capacity improved by a couple orders of magnitude it would be searchable in a few months. We might have to add 10 or 20 bits to the keys at some point. (That's the expansion plan -- "http://perma.cc/ABCD-DEFG-HIJK").

In any event, we do need to allow users (e.g. courts) to make private archives. So if they're not private enough now, the answer's going to be to make them more private, not to open them up.

How about a modified version of my option (2)? We could make non-vested links visible in the detail-view public API (/public/archives/ABCD-1234), but not have them show up in the list (/public/archives/).

**Comment by jcushman** [comment]
OK, I just sent a pull using option (1) -- setting `Access-Control-Allow-Origin: http://perma.cc` for GET requests to /archives/<id> , so users can fetch the updated status of their links. I disabled the spinners for non-logged-in users, which shouldn't really show anyway unless something is broken.

This seems like the best option if we need to support private non-vested links (or potentially lock them down even more), which I think we do.

**Comment by leppert** [comment]
Sounds like a good compromise.
