### ISSUE TITLE
Darchive black bulb for regular users?

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/perma#801]
When vesting users darchive something, we show black bulb on all three available views, including live page view.

But when regular users darchive something, we show black bulb only on the image/warc views, and not on the live page view.

Should we be consistent here?

**Comment by jcushman** [comment]
Matt -- looks like the issue is our check to show the black bulb to the creator of the link is failing. (The intent is to only show the black bulb to the link owner or potential vesters, not to random visitors who just want to see the live view.)

Seems like the same user-comparison issue we already saw -- there are a few more places in single-link.json where we're checking `request.user == linky.created_by` when we should be checking `request.user.pk == linky.created_by.pk`.
