### ISSUE TITLE
Archive vesting API requires trailing slash. This shouldn't be required.

### ISSUE THREAD

**Issue by phillipsm** [harvard-lil/perma#929]
The trailing slash after the guid seems to be required. This shouldn't be the case. Make the trailing slash optional.

This doesn't work,

`curl -H 'Content-Type: application/json' -X PATCH -d '{"vested": "True", "vesting_org": 1, "folder": 27}' https://api.perma.cc/v1/archives/7J9R-2QM5?api_key=your-api-key`

but this does,

`curl -H 'Content-Type: application/json' -X PATCH -d '{"vested": "True", "vesting_org": 1, "folder": 27}' https://api.perma.cc/v1/archives/7J9R-2QM5/?api_key=your-api-key`

**Comment by leppert** [comment]
This is a setting in Tastypie. Happy to take this one.

http://django-tastypie.readthedocs.org/en/latest/settings.html#tastypie-allow-missing-slash

**Comment by phillipsm** [comment]
Cool. Thanks.

**Comment by leppert** [comment]
This has been configured here: https://github.com/harvard-lil/perma/pull/954

But it requires that `APPEND_SLASH` be set to `False`, which affects the entire app, not just the Tastypie endpoints. @jcushman, any thoughts on potential side effects?

**Comment by leppert** [comment]
Looks like there are already a few failing tests as a result.

**Comment by jcushman** [comment]
Those tests are just for the API, right?

For the rest of the app, I think we consistently have `/?` at the end of the url patterns, so APPEND_SLASH won't do anything anyway, because URLs will always match the first time with or without a slash. There's no URL I know of that matches with a slash but doesn't match without a slash, which is the only time APPEND_SLASH will matter. Turning it off should just save a useless check for 404s.

(It's a separate question whether our current setup makes any sense -- probably it would be better to consistently forward from slash to no-slash or vice versa, rather than have both endpoints work.)

**Comment by leppert** [comment]
@jcushman Sounds good. API tests have been fixed. Should be good to merge.

**Comment by leppert** [comment]
Closed by https://github.com/harvard-lil/perma/pull/954
